### ISSUE TITLE
ReportTable fails when only AdapterRemoval has been run

### ISSUE THREAD

**Issue by jfy133** [apeltzer/ReportTable#16]
If an EAGER run has been set up that has only the initial pre-processing and AdapterRemoval modules turned on (nothing downstream other than 'ReportGenerator' and 'Cleanup') ReportTable fails with the following error:
```
Analyzing Sample: TARA_Y100000588
Exception in thread "main" java.lang.NumberFormatException: For input string: "NA"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at analyse.AnalyzeSample.analyseFiles(AnalyzeSample.java:427)
	at analyse.AnalyzeSample.<init>(AnalyzeSample.java:133)
	at main.ReportTable.main(ReportTable.java:83)
```

In the EAGER setup described above, only the following entries are found in the EAGER output directory:

- 0-FastQC
- 1-AdapClip
- 5-DeDup
- 6-QualiMap
- 2017-07-09-12-15-EAGER.xml
- DONE.CleanUpRedundantData
- EAGER.log

**Comment by apeltzer** [comment]
@zxmmx04 What do you need to get that fixed?

**Comment by alex-seitz** [comment]
The current commit (version 1.92.29) should fix that problem

**Comment by jfy133** [comment]
This has not fixed the problem. I recieve pretty much the same error except this line:
`at analyse.AnalyzeSample.analyseFiles(AnalyzeSample.java:439)`

**Comment by alex-seitz** [comment]
I see the problem. It might take some time to fix it. I will write and commit then.

**Comment by alex-seitz** [comment]
Now the lates commit (1.92.30) should work. At least it does here.

**Comment by jfy133** [comment]
Works for me as well now. Thanks!
